packetbeat:
  interfaces:
    device: any
  flows:
    timeout: 30s
    period: 10s
  protocols:
    dns:
      ports: [53]
      include_authorities: true
      include_additionals: true
    http:
      ports: [80, 5601, 9200, 8080, 8081, 5000, 8002]
    memcache:
      ports: [11211]
    mysql:
      ports: [3306]
    pgsql:
      ports: [5432]
    redis:
      ports: [6379]
    thrift:
      ports: [9090]
    mongodb:
      ports: [27017]
    cassandra:
      ports: [9042]
processors:
  - add_cloud_metadata: ~
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:localhost:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  ssl:
    certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    certificate: "/usr/share/elasticsearch/config/certs/packetbeat/packetbeat.crt"
    key: "/usr/share/elasticsearch/config/certs/packetbeat/packetbeat.key"
